#!/usr/bin/env bash
# Print domains and subdomains information

print_domain_subdomain () {
    local domain=$1
    local subdomain=$2
    local full_domain="$subdomain.$domain"
    
    result=$(dig +short "$full_domain")
    if [[ -z "$result" ]]; then
        echo "The subdomain $full_domain does not exist"
        return
    fi
    
    destination=$(echo "$result" | head -n 1)
    if [[ "$destination" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        record_type="A"
    elif [[ "$destination" =~ ^[a-fA-F0-9:]+$ ]]; then
        record_type="AAAA"
    else
        record_type="CNAME"
    fi
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$1" "$2"
elif [ "$#" -eq 1 ]; then
    print_domain_subdomain "$1" "www"
    print_domain_subdomain "$1" "lb-01"
    print_domain_subdomain "$1" "web-01"
    print_domain_subdomain "$1" "web-02"
else
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

